apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-security-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-security-app
  template:
    metadata:
      labels:
        app: cloud-security-app
    spec:
      containers:
      - name: cloud-security-app
        image: au.icr.io/project-7/cloud-security-app:latest  # Update this line
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_SECRET_KEY
          value: "7ef46bb33e976716696f44kubectl apply -f deployment.yaml
5cbd430af4"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-security-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-security-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
